import Navbar from "@/components/navigation/Navbar";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-primary text-secondary lg:h-screen lg:flex`}>
        <header className="sticky w-full top-[calc(100%-4rem)] bg-primary z-10 lg:static lg:top-0 lg:h-full lg:basis-80 xl:basis-96 ">
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
